name: "Space Maker"
description: "A composite GitHub action to free-up disk space by removing large packages and files"

inputs:
  print-package-sizes:
    description: Print out the list of installed packages sorted by size
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Check for Linux OS
      if: runner.os != 'Linux'
      shell: bash
      run: |
        echo "${{ runner.os }} is not suppored"
        exit 1

    - name: Get Ubuntu version
      id: ubuntu_version
      shell: bash
      run: echo "os=$(lsb_release -r -s)" >> $GITHUB_OUTPUT

    - name: Print start disk usage
      shell: bash
      run: df --human-readable --all

    - name: Print package sizes
      if: inputs.print-package-sizes == 'true'
      shell: bash
      run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort --numeric-sort --reverse

    - name: Purge packages (24.04)
      if: steps.ubuntu_version.outputs.os == '24.04'
      shell: bash
      run: |
        sudo apt purge -qq \
          aspnetcore-* \
          azure-* \
          containerd.io \
          containernetworking-plugins \
          linux-headers-* \
          docker-ce* \
          dotnet-* \
          firefox \
          gfortran-* \
          google-chrome-stable \
          kubectl \
          linux-azure-* \
          linux-modules-*-azure \
          microsoft-edge-stable \
          mecab-ipadic \
          mono-* \
          monodoc-* \
          mysql-* \
          podman \
          postgresql-* \
          powershell-* \
          r-base-core \
          vim-runtime

    - name: Purge packages (22.04)
      if: steps.ubuntu_version.outputs.os == '22.04'
      shell: bash
      run: |
        sudo apt purge -qq \
          aspnetcore-* \
          azure-* \
          containerd.io \
          containernetworking-plugins \
          docker-ce* \
          dotnet-* \
          firefox \
          gfortran-* \
          google-chrome-stable \
          google-cloud-cli* \
          kubectl \
          linux-azure-* \
          linux-modules-*-azure \
          microsoft-edge-stable \
          mono-* \
          monodoc-* \
          msbuild \
          mysql-* \
          podman \
          postgresql-* \
          powershell \
          r-base-core \
          vim-runtime

    - name: Purge packages (20.04)
      if: steps.ubuntu_version.outputs.os == '20.04'
      shell: bash
      run: |
        sudo apt purge -qq \
          aspnetcore-* \
          azure-* \
          containerd.io \
          containernetworking-plugins \
          docker-ce* \
          dotnet-* \
          firefox \
          gfortran-* \
          google-chrome-stable \
          google-cloud-cli* \
          kubectl \
          linux-azure-* \
          linux-modules-*-azure \
          microsoft-edge-stable \
          mongodb-* \
          mono-* \
          monodoc-* \
          msbuild \
          mysql-* \
          podman \
          postgresql-* \
          powershell \
          r-base-core \
          vim-runtime

    - name: Autoremove packages
      shell: bash
      run: sudo apt autoremove -qq

    - name: Remove PowerShell Support Files
      shell: bash
      run: sudo rm -rf /usr/local/share/powershell

    - name: Remove Docker Support Files
      shell: bash
      run: sudo rm -rf /var/lib/docker

    - name: Remove Swift Supprt Files
      shell: bash
      run: sudo rm -rf /usr/share/swift

    - name: Print final disk usage
      shell: bash
      run: df --human-readable --all
